### ISSUE TITLE
do not use any packages or features not included in the template

### ISSUE THREAD

**Issue by olesar** [nlpub/dialogue-latex#1]
Could you please suggest how to draw syntactic trees and semantic networks (constituencies, dependencies, HPSG, hierarchical thesauri) if one cannot include userpackages such as `tikz-dependency` and `forest`?

**Comment by dustalov** [comment]
These packages are not supported by the Pandoc tool used in prepress. As a workaround, you can prepare separate PDF illustrations using the `standalone` class and include them as regular images.
