### ISSUE TITLE
in-text references style

### ISSUE THREAD

**Issue by kunilovskaya** [nlpub/dialogue-latex#2]
How about changing the style of intext references to (LastName, YEAR) instead of [4]?
Numbers in the brackets are way less informative and seem to be a common way of formatting.
I checked the Dialogue requirements at http://www.dialog-21.ru/requirements/, and it appears they don't even discuss this issue in their description.

**Comment by dustalov** [comment]
I find this feature very useful for paper authors, but I am afraid it is not properly supported by the conversion process from LaTeX to PageMaker (ICML). We would be happy to accept the patch bringing this functionality, but it should fit our present pipeline.
